#!/usr/bin/env bash

ROS_WS=/home/serial/ros_ws
HOST_WS_DEFAULT=`pwd`
HOST_WS="${1-$HOST_WS_DEFAULT}"
IMAGE_NAME=${SR_IMAGE_NAME:-cyrillg/sr-dev}

if [[ ! -f "$HOST_WS/.catkin_workspace" ]]; then
    echo "The current directory is not a catkin workspace."
    echo "Please verify the path"
    exit 2
fi

res=`docker images --filter=reference=$IMAGE_NAME --format "{{.Repository}}"`
if [[ -z "$res" ]]; then
    echo "Cannot find the $IMAGE_NAME image locally. Please:"
    echo "  - go to the root of the image definition"
    echo "  - run: sr-cli build $IMAGE_NAME"
    exit 1
else
    echo "Creating sr-docker container from $IMAGE_NAME..."
    echo -n " -> "
    docker create \
            -p 5900:5900 \
            -p 12321:22 \
            --volume=$HOST_WS:$ROS_WS:rw \
            --name sr-docker \
            $IMAGE_NAME
fi

