#!/usr/bin/env bash

IMAGE_NAME=${SR_IMAGE_NAME:-cyrillg/sr-dev}

echo -n "Are you sure you want to delete the $IMAGE_NAME image? (y/n) "
read res

if [[ "$res" != "y" ]]; then
    echo "Cancelled"
fi

inst=`docker ps -a --filter=name=sr-docker --format "{{.Names}}"`
if [[ -z "$inst" ]]; then
    echo "No container to reset."
    exit 1
fi

echo "Deleting sr-docker container..."
docker rm sr-docker

echo "Deleting $IMAGE_NAME image..."
docker rmi $IMAGE_NAME

