#!/usr/bin/env bash

img_name=`docker images --filter=reference=cyrillg/sr-dev --format "{{.Repository}}"`
if [[ -z "$img_name" ]]; then
    echo "Image cyrillg/sr-dev does not exist."
else
    echo "Image cyrillg/sr-dev exists."
fi

echo ""

inst=`docker ps -a --filter=name=sr-docker --format "{{.Status}}"`
if [[ -z "$inst" ]]; then
    echo "Container does not exist."
else
    echo "Container exists:"
    echo -n " -> "
    echo $inst
fi

echo ""
