#!/usr/bin/env bash

IMAGE_NAME=${SR_IMAGE_NAME:-cyrillg/sr-dev}

res=`docker images --filter=reference=$IMAGE_NAME --format "{{.Repository}}"`
if [[ -z "$res" ]]; then
    echo "Image $IMAGE_NAME does not exist."
else
    echo "Image $IMAGE_NAME exists."
fi

echo ""

inst=`docker ps -a --filter=name=sr-docker --format "{{.Status}}"`
if [[ -z "$inst" ]]; then
    echo "Container does not exist."
else
    echo "Container exists:"
    echo -n " -> "
    echo $inst
fi

echo ""
